In [2]:
#Bài 1.1
from scipy import linalg
import numpy as np

a = np.array([1, 2, 3])
print("a =", a)

b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
print("b =", b)

c = np.array([[(0.5, 1.5, 10), (3.2, 1.1), (5.4, 7.8, 9.9)]], dtype=object)
print("c =", c)

# Khởi tạo ma trận
A = np.matrix(np.random.random((2, 2)))
print("A =\n", A)

B = np.asmatrix(b)
print("B =\n", B)

C = np.mat(np.random.random((10, 5)))
print("C =\n", C)

D = np.mat([[4, 3], [2, 6]])
print("D =\n", D)

F = np.eye(3, k=1)
print("F (k=1) =\n", F)

F = np.eye(3, k=0)
print("F (k=0) =\n", F)
# Xem hạng ma trận
print("Rank of C:", np.linalg.matrix_rank(C))

# Tính ma trận nghịch đảo
print("Nghịch đảo của A:\n", A.I)

# Định thức ma trận
print("Định thức của A:", linalg.det(A))

# Chuyển vị ma trận
print("A chuyển vị:\n", A.T)
print("A chuyển vị liên hợp:\n", A.H)
# Giả sử A là ma trận vuông và b là vector
b = np.array([1, 2])
print("Nghiệm của phương trình Ax = b:\n", linalg.solve(A, b))

E = np.mat(a).T
print("E =\n", E)

# Giải phương trình xấp xỉ: Ax ≈ b
print("Giải gần đúng Ax ≈ E:\n", linalg.lstsq(F, E)[0])

# Cộng ma trận
print("A + D =\n", np.add(A, D))

# Trừ ma trận
print("A - D =\n", np.subtract(A, D))

# Chia ma trận
#không có

# Nhân ma trận
print("A @ D =\n", A @ D)
print("np.multiply(D, A) =\n", np.multiply(D, A))
print("np.dot(A, D) =\n", np.dot(A, D))
print("np.vdot(A, D) =", np.vdot(A, D))

# Hàm lũy thừa và logarit
print("expm(A) =\n", linalg.expm(A))
print("logm(A) =\n", linalg.logm(A))


a = [1 2 3]
b = [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
c = [[(0.5, 1.5, 10) (3.2, 1.1) (5.4, 7.8, 9.9)]]
A =
 [[0.83120832 0.94572695]
 [0.74991253 0.30376779]]
B =
 [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]


AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

In [3]:
# Bài 2.1
import numpy as np
P = np.array([
    [6, 5, 2, 1],  # Cảnh
    [3, 2, 3, 2],  # Nhật
    [4, 3, 5, 1]   # Hiếu
])
Q = np.array([
    [1.50, 1.00],
    [2.00, 2.50],
    [5.00, 4.50],
    [16.0, 17.0]
])
R = np.dot(P, Q)

print("Ma trận nhu cầu (P):\n", P)
print("\nMa trận giá (Q):\n", Q)
print("\nTổng chi phí (P x Q):\n", R)

people = ["Cảnh", "Nhật", "Hiếu"]
for i in range(len(R)):
    print(f"\nTổng chi phí cho {people[i]}:")
    print(f"  Tại Siêu thị 1: {R[i][0]:.2f} đồng")
    print(f"  Tại Siêu thị 2: {R[i][1]:.2f} đồng")

print("\n=> Gợi ý lựa chọn siêu thị rẻ nhất cho từng người:")
for i in range(len(R)):
    cheaper = "Siêu thị 1" if R[i][0] < R[i][1] else "Siêu thị 2"
    print(f"  {people[i]} nên mua ở {cheaper}.")


Ma trận nhu cầu (P):
 [[6 5 2 1]
 [3 2 3 2]
 [4 3 5 1]]

Ma trận giá (Q):
 [[ 1.5  1. ]
 [ 2.   2.5]
 [ 5.   4.5]
 [16.  17. ]]

Tổng chi phí (P x Q):
 [[45.  44.5]
 [55.5 55.5]
 [53.  51. ]]

Tổng chi phí cho Cảnh:
  Tại Siêu thị 1: 45.00 đồng
  Tại Siêu thị 2: 44.50 đồng

Tổng chi phí cho Nhật:
  Tại Siêu thị 1: 55.50 đồng
  Tại Siêu thị 2: 55.50 đồng

Tổng chi phí cho Hiếu:
  Tại Siêu thị 1: 53.00 đồng
  Tại Siêu thị 2: 51.00 đồng

=> Gợi ý lựa chọn siêu thị rẻ nhất cho từng người:
  Cảnh nên mua ở Siêu thị 2.
  Nhật nên mua ở Siêu thị 2.
  Hiếu nên mua ở Siêu thị 2.


In [4]:
# Bài 2.2
import numpy as np
A = np.array([[2, 1],
              [5, 3]])
B = np.array([[4, -1],
              [2, 1]])

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

print("Ma trận A:\n", A)
print("Ma trận B:\n", B)
print("\nNghịch đảo A⁻¹:\n", A_inv)
print("Nghịch đảo B⁻¹:\n", B_inv)

AB = np.dot(A, B)
print("\nTích AB:\n", AB)

AB_inv = np.linalg.inv(AB)
print("Nghịch đảo của AB (tính trực tiếp):\n", AB_inv)

B_inv_dot_A_inv = np.dot(B_inv, A_inv)
print("B**(-1) * A**(-1) (kiểm tra tính chất):\n", B_inv_dot_A_inv)

print("\nSai số tuyệt đối tối đa giữa (AB)**(-1) và B**(-1) A**(-1):",
      np.max(np.abs(AB_inv - B_inv_dot_A_inv)))


Ma trận A:
 [[2 1]
 [5 3]]
Ma trận B:
 [[ 4 -1]
 [ 2  1]]

Nghịch đảo A⁻¹:
 [[ 3. -1.]
 [-5.  2.]]
Nghịch đảo B⁻¹:
 [[ 0.16666667  0.16666667]
 [-0.33333333  0.66666667]]

Tích AB:
 [[10 -1]
 [26 -2]]
Nghịch đảo của AB (tính trực tiếp):
 [[-0.33333333  0.16666667]
 [-4.33333333  1.66666667]]
B**(-1) * A**(-1) (kiểm tra tính chất):
 [[-0.33333333  0.16666667]
 [-4.33333333  1.66666667]]

Sai số tuyệt đối tối đa giữa (AB)**(-1) và B**(-1) A**(-1): 4.440892098500626e-15


In [7]:
# Bài 2.3
import numpy as np
A = np.array([[0, 1], [1, 0]])
print("Ma trận A:\n", A)

k = 6
temp = A.dot(A)
print("A^2:\n", temp)

for i in range(k - 2):
    temp = temp.dot(A)
    print(f"A^{i+3}:\n", temp)
    print('---')


B = np.array([[0, -1], [-1, 0]])
print("Ma trận B:\n", B)
k = 5
temp = B.dot(B)
print("B^2:\n", temp)

for i in range(k - 2):
    temp = temp.dot(B)
    print(f"B^{i+3}:\n", temp)
    print('---')


C = np.array([[1, 0, 0],
              [1, 0.5, 0],
              [0, 0.5, 1]])

print("Ma trận C:\n", C)

k = 10
temp = C.copy()
for i in range(k - 1):
    temp = temp.dot(C)
print(f"C^{k}:\n", temp)

k = 1000
for i in range(k - 1):
    temp = temp.dot(C)

print(f"C^{1000 + 9} (nhân thêm 1000 lần nữa):\n", temp)




Ma trận A:
 [[0 1]
 [1 0]]
A^2:
 [[1 0]
 [0 1]]
A^3:
 [[0 1]
 [1 0]]
---
A^4:
 [[1 0]
 [0 1]]
---
A^5:
 [[0 1]
 [1 0]]
---
A^6:
 [[1 0]
 [0 1]]
---
Ma trận B:
 [[ 0 -1]
 [-1  0]]
B^2:
 [[1 0]
 [0 1]]
B^3:
 [[ 0 -1]
 [-1  0]]
---
B^4:
 [[1 0]
 [0 1]]
---
B^5:
 [[ 0 -1]
 [-1  0]]
---
Ma trận C:
 [[1.  0.  0. ]
 [1.  0.5 0. ]
 [0.  0.5 1. ]]
C^10:
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.99804688e+00 9.76562500e-04 0.00000000e+00]
 [8.00195312e+00 9.99023438e-01 1.00000000e+00]]
C^1009 (nhân thêm 1000 lần nữa):
 [[1.0000000e+000 0.0000000e+000 0.0000000e+000]
 [2.0000000e+000 1.8227805e-304 0.0000000e+000]
 [1.0070000e+003 1.0000000e+000 1.0000000e+000]]


In [8]:
# Bài 2.4
import numpy as np
M = np.array([[0.8, 0.3],
              [0.2, 0.7]])

M2 = M.dot(M)
print("M^2:")
print(M2)

M3 = M2.dot(M)
print("\nM^3:")
print(M3)
MM = M.copy()
for i in range(100):
    MM = MM.dot(M)

print("\nM^100 (gần với trạng thái ổn định):")
print(MM)

M^2:
[[0.7  0.45]
 [0.3  0.55]]

M^3:
[[0.65  0.525]
 [0.35  0.475]]

M^100 (gần với trạng thái ổn định):
[[0.6 0.6]
 [0.4 0.4]]


In [9]:
# Bài 3.2
import numpy as np
from scipy.linalg import lu

M = np.array([[0.8, 0.3],
              [0.2, 0.7]])
P, L, U = lu(M)

print("Ma trận P:")
print(P)

print("\nMa trận L (tam giác dưới):")
print(L)

print("\nMa trận U (tam giác trên):")
print(U)

print("\nKiểm tra: P @ L @ U = M ban đầu?")
print(np.allclose(P @ L @ U, M))

Ma trận P:
[[1. 0.]
 [0. 1.]]

Ma trận L (tam giác dưới):
[[1.   0.  ]
 [0.25 1.  ]]

Ma trận U (tam giác trên):
[[0.8   0.3  ]
 [0.    0.625]]

Kiểm tra: P @ L @ U = M ban đầu?
True


In [ ]:
# Bài 4
char_to_code = {
    'A': 6, 'B': 7, 'C': 10, 'D': 11, 'E': 13, 'F': 12, 'G': 15, 'H': 16, 'I': 17,
    'K': 18, 'L': 19, 'M': 20, 'N': 21, 'O': 22, 'P': 25, 'Q': 26, 'R': 27,
    'S': 28, 'T': 29, 'U': 30, 'V': 32, 'X': 33, 'Y': 34, ' ': 5, '-': 3, '.': 1
}
code_to_char = {v: k for k, v in char_to_code.items()}
def encrypt_message(message, shift=5):
    encrypted_codes = []
    encrypted_chars = []
    for ch in message:
        ch = ch.upper()
        if ch in char_to_code:
            code = char_to_code[ch]
            new_code = (code + shift) % 36
            encrypted_codes.append(new_code)
            encrypted_chars.append(code_to_char.get(new_code, '*'))
        else:
            encrypted_codes.append(-1)
            encrypted_chars.append('?')
    return encrypted_codes, ''.join(encrypted_chars)

message = "KHOA HO.C DU-LIEU"
codes, encrypted = encrypt_message(message)
print("Chuỗi ban đầu:", message)
print("Mã số:", codes)
print("Chuỗi mã hóa:", encrypted)

In [ ]:
# Bài 5
import numpy as np
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

# Giai đoạn 1 (A)
print("Ma trận A (giai đoạn 1):")
print(A)

# Giai đoạn 2 (A^2)
temp = A.dot(A)
print("\nMa trận A^2 (giai đoạn 2):")
print(temp)

# Giai đoạn 3 (A^3)
temp2 = temp.dot(A)
print("\nMa trận A^3 (giai đoạn 3):")
print(temp2)

# Tổng A + A^2 + A^3
sumA = A + temp + temp2
print("\nTổng A + A^2 + A^3:")
print(sumA)


**BÀI TẬP VỀ NHÀ**

In [10]:
# Bài 1
import numpy as np

# a. Tự chọn một ma trận khả nghịch 3x3
A = np.array([
    [2, 1, 3],
    [1, 2, 1],
    [3, 1, 2]
])
det = np.linalg.det(A)
print("Định thức của A:", det)

if det == 0:
    print("Ma trận không khả nghịch.")
else:
    print("Ma trận khả nghịch. Đây là ma trận nghịch đảo:")
    A_inv = np.linalg.inv(A)
    print(np.round(A_inv, 2))

# b.
text = input("Nhập họ tên hoặc MSSV của bạn: ")

# c.
ascii_values = [ord(char) for char in text]
while len(ascii_values) % 3 != 0:
    ascii_values.append(0)
ascii_matrix = np.array(ascii_values).reshape(-1, 3).T
encoded_matrix = A.dot(ascii_matrix)
print("\nMa trận đã mã hóa:")
print(encoded_matrix)

# d
decoded_matrix = A_inv.dot(encoded_matrix)
decoded_ascii = np.round(decoded_matrix).astype(int).T.flatten()
decoded_chars = [chr(num) for num in decoded_ascii if num != 0]
decoded_text = ''.join(decoded_chars)

print("\nChuỗi sau giải mã:")
print(decoded_text)


Định thức của A: -8.000000000000002
Ma trận khả nghịch. Đây là ma trận nghịch đảo:
[[-0.38 -0.12  0.62]
 [-0.13  0.62 -0.12]
 [ 0.62 -0.12 -0.38]]
Nhập họ tên hoặc MSSV của bạn: hòa

Ma trận đã mã hóa:
[[741]
 [685]
 [748]]

Chuỗi sau giải mã:
hòa


In [11]:
# Bài 2
def continued_fraction(numerator, denominator):
    """Tính toán và biểu diễn phân số liên phân số."""
    result = []
    while denominator:
        quotient = numerator // denominator
        result.append(quotient)
        numerator, denominator = denominator, numerator % denominator
    return result

def to_fraction(continued_frac):
    """Chuyển đổi phân số liên phân số về dạng phân số."""
    n = len(continued_frac)
    if n == 0:
        return (0, 1)

    numerator = 1
    denominator = continued_frac[-1]

    for i in range(n - 2, -1, -1):
        numerator, denominator = denominator, continued_frac[i] * denominator + numerator

    return (denominator, numerator)
num = 8
den = 3

cf = continued_fraction(num, den)
print("Liên phân số:", cf)
frac = to_fraction(cf)
print("Phân số tương ứng:", frac[0], "/", frac[1])

Liên phân số: [2, 1, 2]
Phân số tương ứng: 8 / 3
